server:
  port: 8080

spring:
  application:
    name: campus-activity-system
  datasource:
    url: jdbc:mysql://localhost:3306/campus_activity?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_0900_ai_ci&serverTimezone=Asia/Shanghai
    username: campus
    password: campus123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

app:
  auth-secret: DBPJ-2026-DEMO-SECRET
